[package]
name = "dora-ir"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
melior = { version = "0.19.1", features = [
    "ods-dialects",
] }
mlir-sys = "0.3.0"

[dev-dependencies]
insta = "1.39.0"
