[package]
name = "dora-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude.workspace = true

[lib]
doc = false

[dependencies]
alloy-evm = "0.3.2"
dora.workspace = true
revm.workspace = true
