use crate::dora;

#[derive(Debug, Clone)]
pub enum Operation {
    Add,
    Sub,
    Mul,
    Div,
    SDiv,
    Mod,
    SMod,
    AddMod,
    MulMod,
    Exp,
    SignExtend,
    Lt,
    Gt,
    Slt,
    Sgt,
    Eq,
    IsZero,
    And,
    Or,
    Xor,
    Not,
    Byte,
    Shl,
    Shr,
    Sar,
    Keccak256,
    Address,
    Balance,
    Origin,
    Caller,
    CallValue,
    CalldataLoad,
    CallDataSize,
    CallDataCopy,
    CodeSize,
    CodeCopy,
    GasPrice,
    ExtCodeSize,
    ExtCodeCopy,
    ReturnDataSize,
    ReturnDataCopy,
    ReturnDataLoad,
    ExtCodeHash,
    BlockHash,
    Coinbase,
    Timestamp,
    Number,
    PrevRandao,
    GasLimit,
    ChainId,
    SelfBalance,
    BaseFee,
    BlobHash,
    BlobBaseFee,
    MLoad,
    MStore,
    MStore8,
    SLoad,
    SStore,
    MSize,
    Gas,
    TLoad,
    TStore,
    MCopy,
    Log0,
    Log1,
    Log2,
    Log3,
    Log4,
    Create,
    Call,
    CallCode,
    Return,
    DelegateCall,
    Create2,
    StaticCall,
    Revert,
    Invalid,
    Stop,
    SelfDestruct,
}

impl Operation {
    pub fn name(&self) -> &'static str {
        match self {
            Operation::Stop => dora::StopOperation::name(),
            Operation::Add => dora::AddOperation::name(),
            Operation::Sub => dora::SubOperation::name(),
            Operation::Mul => dora::MulOperation::name(),
            Operation::Div => dora::DivOperation::name(),
            Operation::SDiv => dora::SDivOperation::name(),
            Operation::Mod => dora::ModOperation::name(),
            Operation::SMod => dora::SModOperation::name(),
            Operation::AddMod => dora::AddModOperation::name(),
            Operation::MulMod => dora::MulModOperation::name(),
            Operation::Exp => dora::ExpOperation::name(),
            Operation::SignExtend => dora::SignExtendOperation::name(),
            Operation::Lt => dora::LtOperation::name(),
            Operation::Gt => dora::GtOperation::name(),
            Operation::Slt => dora::SltOperation::name(),
            Operation::Sgt => dora::SgtOperation::name(),
            Operation::Eq => dora::EqOperation::name(),
            Operation::IsZero => dora::IsZeroOperation::name(),
            Operation::And => dora::AndOperation::name(),
            Operation::Or => dora::OrOperation::name(),
            Operation::Xor => dora::XorOperation::name(),
            Operation::Not => dora::NotOperation::name(),
            Operation::Byte => dora::ByteOperation::name(),
            Operation::Shl => dora::ShlOperation::name(),
            Operation::Shr => dora::ShrOperation::name(),
            Operation::Sar => dora::SarOperation::name(),
            Operation::Keccak256 => dora::Keccak256Operation::name(),
            Operation::Address => dora::AddressOperation::name(),
            Operation::Balance => dora::BalanceOperation::name(),
            Operation::Origin => dora::OriginOperation::name(),
            Operation::Caller => dora::CallerOperation::name(),
            Operation::CallValue => dora::CallValueOperation::name(),
            Operation::CalldataLoad => dora::CallDataLoadOperation::name(),
            Operation::CallDataSize => dora::CallDataSizeOperation::name(),
            Operation::CallDataCopy => dora::CallDataCopyOperation::name(),
            Operation::CodeSize => dora::CodeSizeOperation::name(),
            Operation::CodeCopy => dora::CodeCopyOperation::name(),
            Operation::GasPrice => dora::GasPriceOperation::name(),
            Operation::ExtCodeSize => dora::ExtCodeSizeOperation::name(),
            Operation::ExtCodeCopy => dora::ExtCodeCopyOperation::name(),
            Operation::ReturnDataSize => dora::ReturnDataSizeOperation::name(),
            Operation::ReturnDataCopy => dora::ReturnDataCopyOperation::name(),
            Operation::ReturnDataLoad => dora::ReturnDataLoadOperation::name(),
            Operation::ExtCodeHash => dora::ExtCodeHashOperation::name(),
            Operation::BlockHash => dora::BlockHashOperation::name(),
            Operation::Coinbase => dora::CoinbaseOperation::name(),
            Operation::Timestamp => dora::TimestampOperation::name(),
            Operation::Number => dora::NumberOperation::name(),
            Operation::PrevRandao => dora::PrevRandaoOperation::name(),
            Operation::GasLimit => dora::GasLimitOperation::name(),
            Operation::ChainId => dora::ChainIdOperation::name(),
            Operation::SelfBalance => dora::SelfBalanceOperation::name(),
            Operation::BaseFee => dora::BaseFeeOperation::name(),
            Operation::BlobHash => dora::BlobHashOperation::name(),
            Operation::BlobBaseFee => dora::BlobBaseFeeOperation::name(),
            Operation::MLoad => dora::MLoadOperation::name(),
            Operation::MStore => dora::MStoreOperation::name(),
            Operation::MStore8 => dora::MStore8Operation::name(),
            Operation::SLoad => dora::SLoadOperation::name(),
            Operation::SStore => dora::SStoreOperation::name(),
            Operation::MSize => dora::MSizeOperation::name(),
            Operation::Gas => dora::GasOperation::name(),
            Operation::TLoad => dora::TLoadOperation::name(),
            Operation::TStore => dora::TStoreOperation::name(),
            Operation::MCopy => dora::MCopyOperation::name(),
            Operation::Log0 => dora::Log0Operation::name(),
            Operation::Log1 => dora::Log1Operation::name(),
            Operation::Log2 => dora::Log2Operation::name(),
            Operation::Log3 => dora::Log3Operation::name(),
            Operation::Log4 => dora::Log4Operation::name(),
            Operation::Create => dora::CreateOperation::name(),
            Operation::Create2 => dora::Create2Operation::name(),
            Operation::Call => dora::CallOperation::name(),
            Operation::CallCode => dora::CallCodeOperation::name(),
            Operation::DelegateCall => dora::DelegateCallOperation::name(),
            Operation::StaticCall => dora::StaticCallOperation::name(),
            Operation::Return => dora::ReturnOperation::name(),
            Operation::Revert => dora::RevertOperation::name(),
            Operation::Invalid => dora::InvalidOperation::name(),
            Operation::SelfDestruct => dora::SelfDestructOperation::name(),
        }
    }

    #[inline]
    pub fn is_storage_op(&self) -> bool {
        matches!(
            self,
            Operation::SLoad | Operation::SStore | Operation::TLoad | Operation::TStore
        )
    }
}

impl TryFrom<&str> for Operation {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            x if x == dora::StopOperation::name() => Ok(Operation::Stop),
            x if x == dora::AddOperation::name() => Ok(Operation::Add),
            x if x == dora::SubOperation::name() => Ok(Operation::Sub),
            x if x == dora::MulOperation::name() => Ok(Operation::Mul),
            x if x == dora::DivOperation::name() => Ok(Operation::Div),
            x if x == dora::SDivOperation::name() => Ok(Operation::SDiv),
            x if x == dora::ModOperation::name() => Ok(Operation::Mod),
            x if x == dora::SModOperation::name() => Ok(Operation::SMod),
            x if x == dora::AddModOperation::name() => Ok(Operation::AddMod),
            x if x == dora::MulModOperation::name() => Ok(Operation::MulMod),
            x if x == dora::ExpOperation::name() => Ok(Operation::Exp),
            x if x == dora::SignExtendOperation::name() => Ok(Operation::SignExtend),
            x if x == dora::LtOperation::name() => Ok(Operation::Lt),
            x if x == dora::GtOperation::name() => Ok(Operation::Gt),
            x if x == dora::SltOperation::name() => Ok(Operation::Slt),
            x if x == dora::SgtOperation::name() => Ok(Operation::Sgt),
            x if x == dora::EqOperation::name() => Ok(Operation::Eq),
            x if x == dora::IsZeroOperation::name() => Ok(Operation::IsZero),
            x if x == dora::AndOperation::name() => Ok(Operation::And),
            x if x == dora::OrOperation::name() => Ok(Operation::Or),
            x if x == dora::XorOperation::name() => Ok(Operation::Xor),
            x if x == dora::NotOperation::name() => Ok(Operation::Not),
            x if x == dora::ByteOperation::name() => Ok(Operation::Byte),
            x if x == dora::ShlOperation::name() => Ok(Operation::Shl),
            x if x == dora::ShrOperation::name() => Ok(Operation::Shr),
            x if x == dora::SarOperation::name() => Ok(Operation::Sar),
            x if x == dora::Keccak256Operation::name() => Ok(Operation::Keccak256),
            x if x == dora::AddressOperation::name() => Ok(Operation::Address),
            x if x == dora::BalanceOperation::name() => Ok(Operation::Balance),
            x if x == dora::OriginOperation::name() => Ok(Operation::Origin),
            x if x == dora::CallerOperation::name() => Ok(Operation::Caller),
            x if x == dora::CallValueOperation::name() => Ok(Operation::CallValue),
            x if x == dora::CallDataLoadOperation::name() => Ok(Operation::CalldataLoad),
            x if x == dora::CallDataSizeOperation::name() => Ok(Operation::CallDataSize),
            x if x == dora::CallDataCopyOperation::name() => Ok(Operation::CallDataCopy),
            x if x == dora::CodeSizeOperation::name() => Ok(Operation::CodeSize),
            x if x == dora::CodeCopyOperation::name() => Ok(Operation::CodeCopy),
            x if x == dora::GasPriceOperation::name() => Ok(Operation::GasPrice),
            x if x == dora::ExtCodeSizeOperation::name() => Ok(Operation::ExtCodeSize),
            x if x == dora::ExtCodeCopyOperation::name() => Ok(Operation::ExtCodeCopy),
            x if x == dora::ReturnDataSizeOperation::name() => Ok(Operation::ReturnDataSize),
            x if x == dora::ReturnDataCopyOperation::name() => Ok(Operation::ReturnDataCopy),
            x if x == dora::ReturnDataLoadOperation::name() => Ok(Operation::ReturnDataLoad),
            x if x == dora::ExtCodeHashOperation::name() => Ok(Operation::ExtCodeHash),
            x if x == dora::BlockHashOperation::name() => Ok(Operation::BlockHash),
            x if x == dora::CoinbaseOperation::name() => Ok(Operation::Coinbase),
            x if x == dora::TimestampOperation::name() => Ok(Operation::Timestamp),
            x if x == dora::NumberOperation::name() => Ok(Operation::Number),
            x if x == dora::PrevRandaoOperation::name() => Ok(Operation::PrevRandao),
            x if x == dora::GasLimitOperation::name() => Ok(Operation::GasLimit),
            x if x == dora::ChainIdOperation::name() => Ok(Operation::ChainId),
            x if x == dora::SelfBalanceOperation::name() => Ok(Operation::SelfBalance),
            x if x == dora::BaseFeeOperation::name() => Ok(Operation::BaseFee),
            x if x == dora::BlobHashOperation::name() => Ok(Operation::BlobHash),
            x if x == dora::BlobBaseFeeOperation::name() => Ok(Operation::BlobBaseFee),
            x if x == dora::MLoadOperation::name() => Ok(Operation::MLoad),
            x if x == dora::MStoreOperation::name() => Ok(Operation::MStore),
            x if x == dora::MStore8Operation::name() => Ok(Operation::MStore8),
            x if x == dora::SLoadOperation::name() => Ok(Operation::SLoad),
            x if x == dora::SStoreOperation::name() => Ok(Operation::SStore),
            x if x == dora::MSizeOperation::name() => Ok(Operation::MSize),
            x if x == dora::GasOperation::name() => Ok(Operation::Gas),
            x if x == dora::TLoadOperation::name() => Ok(Operation::TLoad),
            x if x == dora::TStoreOperation::name() => Ok(Operation::TStore),
            x if x == dora::MCopyOperation::name() => Ok(Operation::MCopy),
            x if x == dora::Log0Operation::name() => Ok(Operation::Log0),
            x if x == dora::Log1Operation::name() => Ok(Operation::Log1),
            x if x == dora::Log2Operation::name() => Ok(Operation::Log2),
            x if x == dora::Log3Operation::name() => Ok(Operation::Log3),
            x if x == dora::Log4Operation::name() => Ok(Operation::Log4),
            x if x == dora::CreateOperation::name() => Ok(Operation::Create),
            x if x == dora::Create2Operation::name() => Ok(Operation::Create2),
            x if x == dora::CallOperation::name() => Ok(Operation::Call),
            x if x == dora::CallCodeOperation::name() => Ok(Operation::CallCode),
            x if x == dora::DelegateCallOperation::name() => Ok(Operation::DelegateCall),
            x if x == dora::StaticCallOperation::name() => Ok(Operation::StaticCall),
            x if x == dora::ReturnOperation::name() => Ok(Operation::Return),
            x if x == dora::RevertOperation::name() => Ok(Operation::Revert),
            x if x == dora::InvalidOperation::name() => Ok(Operation::Invalid),
            x if x == dora::SelfDestructOperation::name() => Ok(Operation::SelfDestruct),
            _ => Err(()),
        }
    }
}
